/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst,
    output reg high2,
    output reg high1,
    output reg high3,
    output reg low1,
    output reg low2,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    input button,
    input button2
  );
  
  
  
  reg [1:0] rand;
  
  wire [2-1:0] M_ctr_value;
  counter_1 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  always @* begin
    high1 = 1'h0;
    high2 = 1'h0;
    high3 = 1'h0;
    rand = 2'h2;
    
    case (M_ctr_value)
      2'h0: begin
        high1 = 1'h1;
        high2 = 1'h0;
        high3 = 1'h0;
      end
      2'h1: begin
        high1 = 1'h0;
        high2 = 1'h1;
        high3 = 1'h0;
      end
      2'h3: begin
        high1 = 1'h0;
        high2 = 1'h0;
        high3 = 1'h0;
      end
    endcase
    low1 = ~rand[0+0-:1];
    low2 = ~rand[1+0-:1];
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
  end
endmodule
