/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module randomize_1 (
    input clk,
    input rst,
    input [1:0] rowNum,
    output reg [1:0] num
  );
  
  
  
  reg [1:0] num_gen;
  
  wire [32-1:0] M_pn_gen_num;
  reg [1-1:0] M_pn_gen_rst;
  reg [1-1:0] M_pn_gen_next;
  reg [32-1:0] M_pn_gen_seed;
  pn_gen_3 pn_gen (
    .clk(clk),
    .rst(M_pn_gen_rst),
    .next(M_pn_gen_next),
    .seed(M_pn_gen_seed),
    .num(M_pn_gen_num)
  );
  
  always @* begin
    M_pn_gen_rst = rst;
    M_pn_gen_seed = 32'h00000000;
    M_pn_gen_next = 1'h0;
    num_gen = M_pn_gen_num[30+1-:2];
    num = 1'h0;
    if (!rowNum == 2'h3) begin
      M_pn_gen_next = 1'h0;
    end else begin
      M_pn_gen_next = 1'h1;
      if (num_gen == 2'h0) begin
        M_pn_gen_next = 1'h1;
        num_gen = M_pn_gen_num[30+1-:2];
      end else begin
        num = num_gen;
      end
    end
  end
endmodule
