/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module propogate_9 (
    input clk,
    input [2:0] clkinput,
    input rst,
    input [2:0] num,
    output reg [1:0] rowLit,
    output reg [2:0] numOut,
    output reg row1,
    output reg row2,
    output reg row3
  );
  
  
  
  reg clkinvalue;
  
  wire [1-1:0] M_slowclk21_value;
  counter_4 slowclk21 (
    .clk(clk),
    .rst(rst),
    .value(M_slowclk21_value)
  );
  wire [1-1:0] M_slowclk22_value;
  counter_5 slowclk22 (
    .clk(clk),
    .rst(rst),
    .value(M_slowclk22_value)
  );
  wire [1-1:0] M_slowclk23_value;
  counter_6 slowclk23 (
    .clk(clk),
    .rst(rst),
    .value(M_slowclk23_value)
  );
  wire [1-1:0] M_slowclk24_value;
  counter_7 slowclk24 (
    .clk(clk),
    .rst(rst),
    .value(M_slowclk24_value)
  );
  wire [1-1:0] M_slowclk25_value;
  counter_8 slowclk25 (
    .clk(clk),
    .rst(rst),
    .value(M_slowclk25_value)
  );
  
  wire [2-1:0] M_ctr_value;
  counter_12 ctr (
    .clk(clkinvalue),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  always @* begin
    
    case (clkinput)
      3'h0: begin
        clkinvalue = M_slowclk21_value;
      end
      3'h1: begin
        clkinvalue = M_slowclk22_value;
      end
      3'h2: begin
        clkinvalue = M_slowclk23_value;
      end
      3'h3: begin
        clkinvalue = M_slowclk24_value;
      end
      3'h4: begin
        clkinvalue = M_slowclk25_value;
      end
    endcase
    row1 = 1'h0;
    row2 = 1'h0;
    row3 = 1'h0;
    numOut[0+0-:1] = ~num[0+0-:1];
    numOut[1+0-:1] = ~num[1+0-:1];
    numOut[2+0-:1] = ~num[2+0-:1];
    rowLit = M_ctr_value;
    
    case (M_ctr_value)
      2'h0: begin
        row1 = 1'h1;
        row2 = 1'h0;
        row3 = 1'h0;
      end
      2'h1: begin
        row1 = 1'h0;
        row2 = 1'h1;
        row3 = 1'h0;
      end
      2'h2: begin
        row1 = 1'h0;
        row2 = 1'h0;
        row3 = 1'h1;
      end
      2'h3: begin
        row1 = 1'h0;
        row2 = 1'h0;
        row3 = 1'h0;
      end
    endcase
  end
endmodule
