/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module main_2 (
    input clk,
    input rst,
    input bish,
    input bash,
    input shi,
    output reg [2:0] out
  );
  
  
  
  wire [3-1:0] M_bibashi_out;
  reg [1-1:0] M_bibashi_bish;
  reg [1-1:0] M_bibashi_bash;
  reg [1-1:0] M_bibashi_shi;
  bishibashi_detector_3 bibashi (
    .clk(clk),
    .bish(M_bibashi_bish),
    .bash(M_bibashi_bash),
    .shi(M_bibashi_shi),
    .out(M_bibashi_out)
  );
  
  always @* begin
    out = 3'h0;
    M_bibashi_bish = bish;
    M_bibashi_bash = bash;
    M_bibashi_shi = shi;
    if (M_bibashi_out != 1'h0) begin
      out[0+0-:1] = M_bibashi_out[0+0-:1];
      out[1+0-:1] = M_bibashi_out[1+0-:1];
      out[2+0-:1] = M_bibashi_out[2+0-:1];
    end
  end
endmodule
