/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module propogate_2 (
    input clk,
    input rst,
    input [1:0] num,
    output reg [1:0] rowLit,
    output reg [1:0] numOut,
    output reg row1,
    output reg row2,
    output reg row3
  );
  
  
  
  wire [2-1:0] M_ctr_value;
  counter_4 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  always @* begin
    numOut = 2'h0;
    row1 = 1'h0;
    row2 = 1'h0;
    row3 = 1'h0;
    numOut[0+0-:1] = ~num[0+0-:1];
    numOut[1+0-:1] = ~num[1+0-:1];
    rowLit = M_ctr_value;
    
    case (M_ctr_value)
      2'h0: begin
        row1 = 1'h1;
        row2 = 1'h0;
        row3 = 1'h0;
      end
      2'h1: begin
        row1 = 1'h0;
        row2 = 1'h1;
        row3 = 1'h0;
      end
      2'h3: begin
        row1 = 1'h0;
        row2 = 1'h0;
        row3 = 1'h1;
      end
    endcase
  end
endmodule
